### ISSUE TITLE
Use Promises when communicating with db

### ISSUE THREAD

**Issue by Cvos0162** [se701g2/Doto#108]
### User Story: 

As a software engineer, I want to use Promises class so that 
1) it is a better way to handle async operation
2) It is much more self-documenting code then using if statement to catch the error

Promise comes naturally in js. No package has to be given
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

### Acceptance Criteria:
Change the if statement catching an error and use .catch statement with Promises.
1) router.get for /users
2) router.post for /users

**Comment by Dinith1** [comment]
Assigning this to @Cvos0162 as there's a linked PR.

**Comment by cwon880** [comment]
@Cvos0162 is this issue done?

**Comment by Dinith1** [comment]
@cwon880 Looks like the linked PR was abandoned

**Comment by Cvos0162** [comment]
I thought it was going to be handled by other PR...?

**Comment by cwon880** [comment]
Im not too sure could someone from the backend clarify this issue?
