### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by daltonlim** [se701g2/Doto#126]
### User Story: 

As a user, I want a landing page so that I understand what website I'm on.

### Acceptance Criteria:

1) A landing page is present

### Why is the feature required?
To greet any incoming users.
### Describe the solution you'd like
A landing page

**Comment by Cvos0162** [comment]
We might want to consider,
Header,
Title
Brief description of the offered product
Link button to Login
Description of functionality of the product
Footer:
- x Site-map (not needed yet)
- copyrights?

**Comment by baja156** [comment]
Login Page is going to be acting as the landing page
