### ISSUE TITLE
Redirect user to login page from calendar if they are not logged in

### ISSUE THREAD

**Issue by allenwang968** [se701g2/Doto#162]
### User Story: 

As a developer, I want users to not be able to view the calendar if they're not logged in, so that there is privacy.

### Acceptance Criteria:

1) If user is not logged in, any attempts to access any routes that's not login, redirect them back to login page
2) unit tests

**Comment by allenwang968** [comment]
A fix may be found at https://stackoverflow.com/questions/43164554/how-to-implement-authenticated-routes-in-react-router-4. Current user is currently blocked by #158

**Comment by cwon880** [comment]
@allenwang968 update on this?

**Comment by AlexanderTheGrape** [comment]
Note to developers: This issue can be reproduced by going straight to https://doto.azurewebsites.net/calendar as opposed to https://doto.azurewebsites.net . No login is required in this case.
