### ISSUE TITLE
Refactor task route

### ISSUE THREAD

**Issue by allenwang968** [se701g2/Doto#178]
### User Story: 

As a software developer, I want to refactor code so the code can be refactored.

### Acceptance Criteria:

1) refactored code

**Comment by cwon880** [comment]
@allenwang968 @lucycy98 is this issue done?

**Comment by lucycy98** [comment]
this was meant to be changing the task API to only return an ID rather than taking an ID as the inputs, but its already been implemented with frontend so we can disregard this. another ticket has already been made for comments.
