### ISSUE TITLE
Set Up Base project frontend and backend 

### ISSUE THREAD

**Issue by FocalChord** [se701g2/Doto#18]
As a developer, I would like to start development on the project so the base project will need to be set up on the repo

**Acceptance Criteria**
- Frontend folder with a base React project
- Backend folder with backend stack set up
- Should be easily runnable

Blocked by #9 because this is dependent on the CI/CD pipeline

**Comment by cwon880** [comment]
Hi @FocalChord I think this will depend on the CI/CD pipeline that @res550 and I will be setting up so maybe add that as a dependency to this?
