### ISSUE TITLE
Scheduling doesn't use active hours

### ISSUE THREAD

**Issue by Dinith1** [se701g2/Doto#193]
### Bug Summary: 
The scheduling algorithm currently does not take into account the active hours the user specifies in the settings menu.

--- 

### Steps To Reproduce

1) Create a task using the modal such that it gets scheduled in a non-active time

### Expected behaviour

Tasks should only be scheduled in active times, e.g. 9am-9pm

### Observed Behaviour

Tasks are scheduled any time, disregarding active times.

**Comment by TCHE614** [comment]
PR  #260  and  PR #279  closes this issue
