### ISSUE TITLE
Add all-contributors bot to repo

### ISSUE THREAD

**Issue by Matteas-Eden** [se701g2/Doto#204]
### User Story: 

As a software developer, I want this repository to utilise the all-contributors bot so that all types of contributions made by contributors to the project are fairly recognised.

### Acceptance Criteria:

1) All-Contributors bot is installed on this repository
2) Contributions to the project are visible in README

### Notes
https://allcontributors.org/

**Comment by AlexanderTheGrape** [comment]
@all-contributors please add AlexanderTheGrape for code test

**Comment by AlexanderTheGrape** [comment]
Note that this issue is tied to this pull request https://github.com/se701g2/Doto/pull/266
and this issue https://github.com/se701g2/Doto/issues/204 and needs those pull requests to be merged first.
