### ISSUE TITLE
Crash when visiting /calendar while unauthenticated

### ISSUE THREAD

**Issue by jordansimsmith** [se701g2/Doto#205]
### Bug Summary: 
When visiting the /calendar page without authenticating first, a crash is observed.

--- 

### Steps To Reproduce

1) Make sure that you are not logged in
2) Visit the /calendar page directly (by URL), don't log in through google

### Expected behaviour
Redirection to the login page or an unauthorised error page.

### Observed Behaviour
Calendar page is loaded and an internal error is produced.

### Screenshots
![ss](https://user-images.githubusercontent.com/18223858/77585574-8ef5f180-6f49-11ea-865f-9b057364e3e4.png)

### Environment

- Version: 57196ec

- Operating System: Manjaro Linux
- Browser (if any): Chromium

---

**Comment by HarrisonLeach1** [comment]
Isn't this a duplicate of #162 ?

**Comment by jordansimsmith** [comment]
> Isn't this a duplicate of #162 ?

Good spotting, I’ll mark as duplicate and close.
