### ISSUE TITLE
Incorrect callback URL port when developing

### ISSUE THREAD

**Issue by jordansimsmith** [se701g2/Doto#206]
### Bug Summary: 
When developing, create react app allows you to change the port (useful if you have something else running on port 3000). However, when authenticating on a non 3000 port, the callback url will assume you are on port 3000, and will not redirect you to the doto application.

--- 

### Steps To Reproduce

1) Open another application on port 3000
2) Launch doto-frontend and select yes to opening on another port
3) attempt to login with google

### Expected behaviour

Callback URL should be correct, you should be redirected back to doto after login.
### Observed Behaviour

Callback URL was incorrect, redirects to the other application running on port 3000
### Environment

- Version: 57196ec
- Operating System: Manjaro Linux
- Browser (if any): Chromium

---

**Comment by Matteas-Eden** [comment]
I'm tempted to say this bug is part of the design, given this extract from the README:

> By default, the react-app is hosted on port 3000 and the local server is hosted on port 3001. Do not change these numbers as we have added the addresses as authorized redirect uri's in our google credentials.

**Comment by jordansimsmith** [comment]
> I'm tempted to say this bug is part of the design, given this extract from the README:
> 
> > By default, the react-app is hosted on port 3000 and the local server is hosted on port 3001. Do not change these numbers as we have added the addresses as authorized redirect uri's in our google credentials.

Good spotting, yeah I agree with you. I must have missed that part :laughing:. I'll close the issue.
