### ISSUE TITLE
Unable to run backend testing suite

### ISSUE THREAD

**Issue by Matteas-Eden** [se701g2/Doto#211]
### Bug Summary: 

When attempting to run the tests on `doto-backend`, the testing suite immediately throws an error upon failing to connect to `127.0.0.1:27017`.

--- 

### Steps To Reproduce

1) `cd doto-backend`
2) `npm test`

### Expected behaviour

The testing suite should run, evaluating each test in turn and producing messages in console regarding the pass/fail behaviour.

### Observed Behaviour

The testing suite fails to start, throwing an error message.

### Screenshots

![DotoBackendTestError](https://user-images.githubusercontent.com/45587386/77697683-2cb5f300-7014-11ea-8cf2-c8a2af4b1505.png)

### Environment

- Version: 57196ec
- Operating System: Arch Linux
- Browser (if any):

---

### Stack Traces

```
❯ npm test

> doto-backend@1.0.0 test /home/matteas/Documents/University/SE701/Doto/doto-backend
> mocha



  Task Model Tests
(node:2132) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/home/matteas/Documents/University/SE701/Doto/doto-backend/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:315:20)
    at /home/matteas/Documents/University/SE701/Doto/doto-backend/node_modules/mongodb/lib/core/connection/pool.js:561:14
    at /home/matteas/Documents/University/SE701/Doto/doto-backend/node_modules/mongodb/lib/core/connection/pool.js:994:11
    at /home/matteas/Documents/University/SE701/Doto/doto-backend/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/home/matteas/Documents/University/SE701/Doto/doto-backend/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/home/matteas/Documents/University/SE701/Doto/doto-backend/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}
npm ERR! Test failed.  See above for more details.

```

**Comment by salma-s** [comment]
Hi @Matteas-Eden , I fixed this same issue by installing and running [MongoDB](https://docs.mongodb.com/manual/administration/install-community/). I've found that the tests run successfully with `npm test` only if the mongod process is alive on my machine.

Hopefully this works for you!

**Comment by Matteas-Eden** [comment]
The wiki page [Testing (Backend)](https://github.com/se701g2/Doto/wiki/Testing-(Backend)) has been updated with the above information which resolves this bug.
