### ISSUE TITLE
Edit or delete tasks

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [se701g2/Doto#212]
### User Story: 

As a user, I want to be able to edit or delete a task so that if I've incorrectly put in a task or want to change or delete it, I can easily do so

### Acceptance Criteria:

1) You are able to edit a created task (probably using the same display used to create the task
2) You can delete a task

### Why is the feature required?
You can't currently edit or delete a task

### Describe the solution you'd like
When you click on the task, along with the current pop up, there would be an edit button and a delete button that you can use to change/remove the task.

**Comment by harmanlamba** [comment]
Hiya @KimberleyEvans-Parker, Team # 4 (@salma-s , @EricPedrido , and I) were thinking this would best be broken into two separate issues, that we would want to tackle. Hence, we are going to be replacing this issue with the following Issues #220 and #221 

@KimberleyEvans-Parker , would that be ok? Please feel free to close the issue once, the other two have been approved.

**Comment by EricPedrido** [comment]
The new issues regarding these feature requests are #220 and #221.
