### ISSUE TITLE
Ability to complete a task

### ISSUE THREAD

**Issue by HarrisonLeach1** [se701g2/Doto#213]
### User Story: 

As a user, I want to be able to complete a task so that I can track when I meet my commitments and when I do not.

### Acceptance Criteria:
1) Can complete an item from both the list view and calendar view.
2) Completed items have a clear indication that they are completed
3) Completed items are not deleted (because the user wants to keep track of past progress)
4)  Upon completion of an item, the status is sent to the backend and persisted.

### Why is the feature required?
In to-do apps you are typically able to complete items. This allows users to keep track of what they've done. 

### Describe the solution you'd like
You can cross off items and they are visibly different.

#### Calendar View
![Task expand](https://i.imgur.com/xs3CMNs.png)

#### List View
![Task view](https://imgur.com/lvuJvYt.png)

**Comment by HarrisonLeach1** [comment]
Let me know what you guys think about AC 3.

**Comment by HarrisonLeach1** [comment]
Blocks #62

**Comment by HarrisonLeach1** [comment]
Also, should you be able to 'uncomplete' a task

**Comment by Matteas-Eden** [comment]
> Let me know what you guys think about AC 3.

I think it seems quite reasonable.
