### ISSUE TITLE
Edit tasks

### ISSUE THREAD

**Issue by EricPedrido** [se701g2/Doto#221]
### User Story: 

As a user, I want to have the flexibility to make changes to tasks so that I can easily correct a task if I have made a mistake or decide to change my mind.

### Acceptance Criteria:

1) You are able to edit an already created task.
2) The edit is saved in the database.

### Why is the feature required?

You can't currently edit tasks.

### Describe the solution you'd like

When you click on a task, an edit button pop up appears, which will take you to another page (probably the same as creating a task) to edit the existing task.

**Comment by PreetPatel** [comment]
will investigate
