### ISSUE TITLE
Repeating tasks

### ISSUE THREAD

**Issue by nikotj1** [se701g2/Doto#224]
### User Story: 

As a user, I want to be able to extend tasks to the next day or more at the same time so that repeating tasks won't have to be individually added

### Acceptance Criteria:

1) An indication that you can add the same task to the right (next day)
2) The new task is saved in the database

Illustration:
![step_2](https://user-images.githubusercontent.com/43423740/77993455-b2270380-7384-11ea-8f86-b89283473e7a.jpg)

![step_1](https://user-images.githubusercontent.com/43423740/77993439-a9cec880-7384-11ea-9f2c-aed6eb4b256d.JPG)

**Comment by Kalashnikkov** [comment]
I feel like this feature is not needed with the current implementation and point of this app, Should we close this one out guys? (Should input tasks, allocate you time to do a task, and show you when you should do those tasks - there should really be no need for 'repeating tasks')

@nikotj1  @rmoradc could I get some input here?

**Comment by Minus20Five** [comment]
Copied from PR #270 

> If you decide to implement recurring tasks I would recommend following the [dev express API](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointments/#recurring-appointments). Theres also a built-in component to [edit recurring tasks](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/edit-recurrence-menu/).

**Comment by nikotj1** [comment]
Thanks for the input guys. I see how it's against the nature of our app as we'd want the user to have as little interaction with the app as possible, however, I can still see the value for a user to be able to manipulate their schedule.

**Comment by Minus20Five** [comment]
Seems like this issue should be closed.
