### ISSUE TITLE
Add authorisation to the update task endpoint

### ISSUE THREAD

**Issue by HarrisonLeach1** [se701g2/Doto#229]
### User Story: 

As a user, I want to have authorisation on the update task endpoint so that my task data cannot be modified.

### Acceptance Criteria:

1) Tasks can only be updated by their owners. 
2) Appropriate documentation is updated. Including the wiki [here](https://github.com/se701g2/Doto/wiki/API-Documentation#updatetask)

### Notes

- The exact endpoint is `PUT /task/:taskId`

- Currently, unauthorised users can update all fields of a task such as its title, start and end time and completion status
- The demo below demonstrates this current behaviour:

![Untitled_ Apr 5, 2020 11_24 PM (1)](https://user-images.githubusercontent.com/44953072/78473538-84332c00-7795-11ea-8df0-3705eb412795.gif)

**Comment by Matteas-Eden** [comment]
It appears that this issue was resolved by another PR (#213), as the behaviour described here cannot be reproduced.
