### ISSUE TITLE
Adding and completing two or more new tasks in one session doesn't work.

### ISSUE THREAD

**Issue by bradleycoleman** [se701g2/Doto#240]
### Bug Summary: 

If more than one task is added in a single session, then opening the popup for any of them and attempting to toggle their completeness will only toggle the completeness of the task scheduled first, even if it is marked as complete in the correct order.
--- 

### Steps To Reproduce

1) Create two new tasks 
2) Attempt to toggle the completeness of the second scheduled task

### Expected behaviour

The second task is marked as complete.

### Observed Behaviour

The first task is marked as complete. Any further toggling of either tasks' completeness will only affect the first task until you refresh. 

### Screenshots
Two tasks are added:
![image](https://user-images.githubusercontent.com/43105616/78850440-55ee6e80-7a6b-11ea-8d25-22391496157a.png)

I attempt to mark the second as complete, but it actually marks the first. If the first task is marked as complete first, then it will be marked as incomplete when you attempt to complete the second:

![image](https://user-images.githubusercontent.com/43105616/78850469-67d01180-7a6b-11ea-8f42-fcf0b972e1c9.png)

### Environment

- Version: Commit [bd15bc5d](https://github.com/se701g2/Doto/commit/bd15bc5d). 
- Operating System: Windows 10
- Browser (if any): Chrome

---

**Comment by HarrisonLeach1** [comment]
Nice one @bradleycoleman

**Comment by HarrisonLeach1** [comment]
This is potentially caused by #250 so we will have to wait till that is fixed before work can begin on this.

**Comment by PreetPatel** [comment]
Done
