### ISSUE TITLE
Task list should show the task start time and end time

### ISSUE THREAD

**Issue by qibao0722** [se701g2/Doto#247]
### User Story: 

As a user, I want to see the task start time and due time  from the task list 

so that I know clearly when should I do the task

![image](https://user-images.githubusercontent.com/53366211/79395670-453f7a80-7fce-11ea-9663-b94ce16bbe72.png)

### Acceptance Criteria:

1) Tasklist shows the task start time and end time

**Comment by jordansimsmith** [comment]
I think that showing the start time is sufficient, as that is more important to the user than the end time.
