### ISSUE TITLE
Switching themes sometimes does not occur immediately

### ISSUE THREAD

**Issue by HarrisonLeach1** [se701g2/Doto#248]
### Bug Summary: 
Upon switching themes on the settings page sometimes it flashes the old theme for a short period then reverts back to the new theme. 

--- 

### Steps To Reproduce

1) Go to the settings page 
2) Change theme
3) Keep repeating step 2

### Expected behaviour
Every time the theme is changed colours should only change once. 

### Observed Behaviour
Sometimes the old theme will flash when changing themes.

### Screenshots
![Doto](https://user-images.githubusercontent.com/44953072/79408449-7c725380-7fef-11ea-8e14-8024379ca93d.gif)

### Environment

- Version: Commit [9fab8f0](https://github.com/se701g2/Doto/commit/9fab8f0)
- Operating System: Ubuntu 18.04
- Browser (if any): Chrome v75

**Comment by PreetPatel** [comment]
will investigate

**Comment by PreetPatel** [comment]
fix: https://github.com/se701g2/Doto/pull/255
