### ISSUE TITLE
Task gets created without task ID

### ISSUE THREAD

**Issue by salma-s** [se701g2/Doto#250]
### Bug Summary: 
When a new task gets added, it initially has no `taskId` associated until refresh.

--- 

### Steps To Reproduce

1) Add a new task

### Expected behaviour

When you add a new task, it should have a `taskId` associated with it.

### Observed Behaviour

When you add a new task, the `taskId` is undefined until a refresh happens, which loads a `taskId` from the database.

### Environment

- Operating System: Windows
- Browser (if any): Chrome

---
### Other
 This bug was found by @salma-s @EricPedrido and @harmanlamba

**Comment by HarrisonLeach1** [comment]
This is potentially a root cause of #240 and #252
