### ISSUE TITLE
Change UI for creating new task

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [se701g2/Doto#269]
### User Story: 

As a user, I want the create task's side bar to re-adjust itself on different window sizes so that text is always readable

### Acceptance Criteria:

1) The colour bar and doesn't overlap with the text (image shown below)

### Notes
Could probably be solved by limiting the height of the pop-up 'add task' window size.

![image](https://user-images.githubusercontent.com/45865186/79818426-e1f18600-83db-11ea-99ce-21c83cef1e1e.png)

**Comment by Matteas-Eden** [comment]
Upon investigation, it turns out that this was already fixed in #199. As such, I'm closing this issue.
