### ISSUE TITLE
Research and create a license

### ISSUE THREAD

**Issue by FocalChord** [se701g2/Doto#4]
As a developer I want to pick a license to allow for further open source collaboration

**Acceptance Criteria:**
- Discovery on license is done and presented
- A license is selected
- A license is committed

**Comment by res550** [comment]
Was this being close from our PR templates? @daltonlim

**Comment by daltonlim** [comment]
@res550 yeah. I believe all the prs with the old template are now closed so this shouldn't happen anymore.
