### ISSUE TITLE
Setup Precommit Hooks for Git

### ISSUE THREAD

**Issue by res550** [se701g2/Doto#45]
### User Story: 

As a software developer, I want my linting and test cases to run when I commit so that I can be sure that my build works and the style rules are followed.

### Acceptance Criteria:

1) On commit, to Github the prettier and eslint rules are applied
2) Tests will also be run on commit

**Comment by FocalChord** [comment]
@res550 This was done in the frontend when I set up linting. See Issue #31 .

**Comment by res550** [comment]
Okay cool ill just put the unit tests in then

**Comment by res550** [comment]
Going to close this after discussing further it doesn't seem valuable as it just stop developers from using TDD if they choose to do so since you cant commit until all tests pass
