### ISSUE TITLE
Define coding conventions

### ISSUE THREAD

**Issue by tnzhu** [se701g2/Doto#54]
### User Story: 

As a developer, I want to establish coding conventions so that all code is written in a uniform manner.

### Acceptance Criteria:

1) Create a wiki page that outlines the coding conventions to be used
2) Ensure all developers are aware of these conventions

**Comment by Dinith1** [comment]
Added the coding conventions page to the wiki: https://github.com/se701g2/Doto/wiki/Coding-Conventions
