### ISSUE TITLE
Set up routes for backend

### ISSUE THREAD

**Issue by tnzhu** [se701g2/Doto#56]
### User Story: 

As a developer, I want to create the endpoints for Users and Tasks so that requests from front-end can be processed. 

### Acceptance Criteria:
1) Update routes for User to reflect those outlined in the README
1) Add CRUD operations for Tasks into router.js
2) Pass unit tests  

### Why is the feature required?
Routing needs to be set up to process requests from front-end and to manage the storage of data in the database

### Describe the solution you'd like
Create endpoints for creation, read, update and deletion for Task

### Additional Context:
Depends on Issue#40 
Refer to the README in the backend directory for what endpoints should be created.

**Comment by Cvos0162** [comment]
@tnzhu is there any existing schema/model for these Tasks?

**Comment by tnzhu** [comment]
> @tnzhu is there any existing schema/model for these Task?

Yup, @emzoo16 is still working on the schema, so we're waiting for that to be done before creating the routes/endpoints for anything related to Task

**Comment by Cvos0162** [comment]
> > @tnzhu is there any existing schema/model for these Task?
> 
> Yup, @emzoo16 is still working on the schema, so we're waiting for that to be done before creating the routes/endpoints for anything related to Task

cool, thanks

**Comment by lucycy98** [comment]
@shane-dp @jonathanvenema98 how is this going? If you want some help or someone to look over what you've done so far, feel free to create a pr and just make a note that it is still WIP

**Comment by jonathanvenema98** [comment]
API for Users seems to be working fine
Currently stuck on testing out the scheduling API, specifically the ones with params (':username') attached to the end of it.
Specifically, if anything is passed that is not the ':id', I don't know how to use this further, ie return all schedules that contain the same user.

**Comment by lucycy98** [comment]
@jonathanvenema98 are you having problems with dealing with the db itself or the payload? anyway, might be a good idea to create a pr on what you've done so far and i can help

**Comment by Cvos0162** [comment]
#108 
#109 
I've thought that using promise class to handle connections to db, as it is async operations. Promise object is so much natural to js and to humans.
