### ISSUE TITLE
Implementing the gamification/point system for completed tasks

### ISSUE THREAD

**Issue by baja156** [se701g2/Doto#62]
### User Story: 

As a software developer, I want to add a point system/gamification to my app Todo so that the users have incentive to complete their tasks.

### Acceptance Criteria:

1) A seamless UI for the point system implemented. Functionality is not necessary at the moment

### Why is the feature required?
To provide incentive for the users to complete their tasks and to make our to-do app a little more fun and interactive.

**Comment by HarrisonLeach1** [comment]
Blocked by #213
