### ISSUE TITLE
MongoDb error in Backend Deployment

### ISSUE THREAD

**Issue by res550** [se701g2/Doto#70]
### Bug Summary: 

We have an error where the backend CD is failing due to an issue running the tests. This is caused by failing to start up the mongodb
--- 
### Steps To Reproduce

1) Run the CD on master branch in the se701g2/Doto repository

### Expected behaviour

We expect the deploy to be successful to azure

### Observed Behaviour

CD failed due to a failing test caused by mongodb not starting.

**Comment by cwon880** [comment]
Looks like the MongoDB action we are using is only supported in Linux. Where as our backend deployment is on Windows

**Comment by res550** [comment]
Will continue working from this issue to resolve I think best approach will be to just remove test from deploy since it would have already run tests before a PR.

**Comment by daltonlim** [comment]
Looks like the merge conflict fix re-added the mongoDB tests and are failing again.
