### ISSUE TITLE
Document backend API

### ISSUE THREAD

**Issue by Dinith1** [se701g2/Doto#84]
### User Story: 

As a devloper, I want what the backend API offers in terms of endpoints/data schemas and authentication processes, so that call the API as needed for any frontend features.

### Acceptance Criteria:

1) All endpoints should be documented, including http method, url and data returned in the Wiki.
2) description of database schemas and what each field means
3) description of how the authentication login process works

**Comment by lucycy98** [comment]
done the db schema and API documentation
waiting for @emzoo16 to write documentation authentication

**Comment by emzoo16** [comment]
Did the documentation for authentication. Should we remove add new user and login since those are both done through google?
